config/routes.rb
Rails.application.routes.draw do
  resources :owndoms
  resources :countries
  resources :cities
  resources :owners
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root to: 'administration#index'

  namespace :api, constraints: { format: 'json' }  do
    namespace :v1 do
      get 'owndoms/:id' => 'owndoms#show'
      get 'owndoms'     => 'owndoms#index'
    end
  end
end

app/models/api/v1/owndoms.rb
module Api
  module V1
    class Owndoms
      attr_reader :params

      def initialize(params)
        @params  = params
      end

      def list
        Owndom.by_query(params[:query])
      end

      def show
        Owndom.find(params[:id])
      end
    end
  end
end

app/models/owndom.rb
class Owndom < ApplicationRecord
  belongs_to :owner
  belongs_to :country
  belongs_to :city

  accepts_nested_attributes_for :owner, :city, :country

  def as_json(options = {})
    super(include: [:owner, :country, :city])
  end

  def self.by_query(query)
    return where(nil) unless query.present?

    joins(:city).
    joins(:country).
    joins(:owner).
    where('LOWER(cities.name) LIKE :query OR LOWER(countries.name)  LIKE :query OR LOWER(owners.name) LIKE :query OR
      LOWER(address1) LIKE :query OR LOWER(address2) LIKE :query OR LOWER(address3) LIKE :query OR LOWER(address4) LIKE :query
      OR LOWER(post_code) LIKE :query', query: "%#{query.downcase}%")
  end
end

app/controllers/api/v1/owndoms_controller.rb
class Api::V1::OwndomsController < Api::BaseController

  def index
    @owndoms = Api::V1::Owndoms.new(params).list
  end

  def show
    @owndom = Api::V1::Owndoms.new(params).show
  end
end

app/controllers/owndoms_controller.rb
class OwndomsController < ApplicationController
  before_action :set_owndom, only: [:show, :edit, :update, :destroy]

  # GET /owndoms
  # GET /owndoms.json
  def index
    @owndoms = Owndom.all
  end

  # GET /owndoms/1
  # GET /owndoms/1.json
  def show
  end

  # GET /owndoms/new
  def new
    @owndom = Owndom.new
  end

  # GET /owndoms/1/edit
  def edit
  end

  # POST /owndoms
  # POST /owndoms.json
  def create
    @owndom = Owndom.new(owndom_params)

    respond_to do |format|
      if @owndom.save
        format.html { redirect_to @owndom, notice: 'Owndom was successfully created.' }
        format.json { render :show, status: :created, location: @owndom }
      else
        format.html { render :new }
        format.json { render json: @owndom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owndoms/1
  # PATCH/PUT /owndoms/1.json
  def update
    respond_to do |format|
      if @owndom.update(owndom_params)
        format.html { redirect_to @owndom, notice: 'Owndom was successfully updated.' }
        format.json { render :show, status: :ok, location: @owndom }
      else
        format.html { render :edit }
        format.json { render json: @owndom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owndoms/1
  # DELETE /owndoms/1.json
  def destroy
    @owndom.destroy
    respond_to do |format|
      format.html { redirect_to owndoms_url, notice: 'Owndom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owndom
      @owndom = Owndom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owndom_params
      params.require(:owndom).permit(:address1, :address2, :address3, :address4, :post_code, :income)
    end
end

app/helpers/owndoms_helper.rb
module OwndomsHelper
end

app/views/owndoms/_form.html.slim
= form_with(model: owndom, local: true) do |form|
  - if owndom.errors.any?
    #error_explanation
      h2 #{pluralize(owndom.errors.count, "error")} prohibited this owndom from being saved:
      ul
        - owndom.errors.full_messages.each do |message|
          li = message

  .field
    = form.select :owner_id, options_from_collection_for_select(Owner.all, :id, :name, owndom.owner_id), {include_blank: "Owner", required: true }

  .field
    = form.label :address1
    = form.text_field :address1, id: :owndom_address1, required: true


  .field
    = form.label :address2
    = form.text_field :address2, id: :owndom_address2


  .field
    = form.label :address3
    = form.text_field :address3, id: :owndom_address3


  .field
    = form.label :address4
    = form.text_field :address4, id: :owndom_address4, required: true


  .field
    = form.label :post_code
    = form.text_field :post_code, id: :owndom_post_code


  .field
    = form.label :income
    = form.text_field :income, id: :owndom_income

  .field
    = form.select :country_id, options_from_collection_for_select(Country.all, :id, :name, owndom.country_id), {include_blank: "Country", required: true }

  .field
    = form.select :city_id, options_from_collection_for_select(City.all, :id, :name, owndom.city_id), {include_blank: "City", required: true }


  .actions
    = form.submit

app/views/owndoms/edit.html.slim
.demo-card-square.mdl-card.mdl-shadow--2dp
  .mdl-card__title.mdl-card--expand
    h2.mdl-card__title-text Editing Propertie
  .mdl-card__supporting-text
    = render 'form', owndom: @owndom
  .mdl-card__actions.mdl-card--border
    = link_to 'Show', @owndom, class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored"
    = link_to 'Back', owndoms_path, class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored"

app/views/owndoms/index.html.slim
p#notice = notice

h5.white Properties

table.mdl-data-table.mdl-js-data-table
  thead
    tr
      th Address1
      th Address2
      th Address3
      th Address4
      th Post code
      th Income
      th colspan="3"

  tbody
    - @owndoms.each do |owndom|
      tr
        td = owndom.address1
        td = owndom.address2
        td = owndom.address3
        td = owndom.address4
        td = owndom.post_code
        td = owndom.income
        td = link_to 'Show', owndom
        td = link_to 'Edit', edit_owndom_path(owndom)
        td = link_to 'Destroy', owndom, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Owndom', new_owndom_path, class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored"

app/views/owndoms/new.html.slim
.demo-card-square.mdl-card.mdl-shadow--2dp
  .mdl-card__title.mdl-card--expand
    h2.mdl-card__title-text New Propertie
  .mdl-card__supporting-text
    = render 'form', owndom: @owndom
  .mdl-card__actions.mdl-card--border
    = link_to 'Back', owndoms_path, class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored"

app/views/owndoms/show.html.slim
p#notice = notice
.demo-card-square.mdl-card.mdl-shadow--2dp
  .mdl-card__title.mdl-card--expand
    h2.mdl-card__title-text #{@owndom.owner.name} propertie
  .mdl-card__supporting-text
    p
      strong Address1:
      = @owndom.address1
    p
      strong Address2:
      = @owndom.address2
    p
      strong Address3:
      = @owndom.address3
    p
      strong Address4:
      = @owndom.address4
    p
      strong Post code:
      = @owndom.post_code
    p
      strong Income:
      = @owndom.income
  .mdl-card__actions.mdl-card--border
    = link_to 'Edit', edit_owndom_path(@owndom), class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored"
    = link_to 'Back', owndoms_path, class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored"